name: Build and Push Docker image for client-web to DockerHub
on:
  push:
    branches:
      - main
    paths:
      - '/client-web/**'
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-actions@v4
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./client-web
          file: ./Dockerfile.build
          push: ${{ github.ref_type == 'tag' }}
          tags: dappros/web
