name: Build and Push Docker image for client-web to DockerHub

on:
	push:
		branches:
			- main
		path:
			- '/client-web/**'
	jobs:
		push_to_registry:
			name: Push Docker image to Docker Hub
			runs-on: ubuntu-latest
			steps:
				- name: Check out the repo
					uses: actions/checkout@v3